<?php

/*************************************
*      Generated Autopilot file      *
*     ---------------------------    *
*Autopilot Generated By Dapperstrano *
*     ---------------------------    *
*************************************/

Namespace Core ;

class AutoPilotConfigured extends AutoPilot {

    public $steps ;

    public function __construct() {
	    $this->setSteps();
    }

    /* Steps */
    private function setSteps() {

	    $this->steps =
	      array(

              array ( "Logging" => array( "log" => array( "log-message" => "Starting Dapperstrano Application Configuration of Virtual Machine Host"), ) ),

              array ( "Logging" => array( "log" => array( "log-message" => "Create our host file entry for our local URL"), ) ),
              array ( "HostEditor" => array( "add" => array (
                  "guess" => true,
                  "host-name" => "<%tpl.php%>dap_apache_vhost_url</%tpl.php%>",
              ), ), ),

              array ( "Logging" => array( "log" => array( "log-message" => "Dapperstrano Application Configuration of Virtual Machine Host Complete", ), ), ),

	      );

	  }
}
