<?php

/*************************************
 *      Generated Autopilot file      *
 *     ---------------------------    *
 *Autopilot Generated By Dapperstrano *
 *     ---------------------------    *
 *************************************/

Namespace Core ;

class AutoPilotConfigured extends AutoPilot {

    public $steps ;

    protected $url ;
    protected $sourceDir ;

    public function __construct() {
        parent::__construct(array());
        $this->setUrl() ;
        $this->setSourceDir() ;
        $this->setSteps();
    }

    /* Steps */
    protected function setSteps() {

        $this->steps =
            array(

                array ( "Logging" => array( "log" => array( "log-message" => "Add our host entry"), ) ),
                array ( "HostEditor" => array( "add" => array (
                    "guess" => true,
                    "host-name" => "{$this->getUrl()}",
                ), ), ),

                array ( "Logging" => array( "log" => array( "log-message" => "Create our virtual host"), ) ),
                array ( "ApacheVHostEditor" => array( "add" => array (
                    "guess" => true,
                    "vhe-docroot" => "{$this->getSourceDir()}",
                    "vhe-url" => "{$this->getUrl()}",
                    "vhe-ip-port" => "127.0.0.1:80",
                    "vhe-template" => $this->getTemplate(),
                ), ), ),

                array ( "Logging" => array( "log" => array( "log-message" => "Now lets restart Apache so we are serving our new application", ), ), ),
                array ( "ApacheControl" => array( "restart" => array(
                    "guess" => true,
                ), ), ),

                array ( "Logging" => array( "log" => array("log-message" => "Our Papyrus Editor monitor is installed" ), ), ),

            );

    }

    protected function setUrl() {
        if (isset($this->params["papyruseditor-url"])) {
            $this->url = $this->params["papyruseditor-url"] ;
            return ; }
        $question = "What is the local URL you would like for your Papyrus Editor Interface?" ;
        $answer = $this->askForInput($question, true) ;
        $this->url = $answer ;
    }

    protected function getUrl() {
        return $this->url ;
    }

    protected function setSourceDir() {
        if (isset($this->params["source-dir"])) {
            $this->sourceDir = $this->params["source-dir"] ;
            return ; }
        $question = "What is the Source Directory containing the files?" ;
        $answer = $this->askForInput($question, true) ;
        $this->sourceDir = $answer ;
    }

    protected function getSourceDir() {
        return $this->sourceDir ;
    }

    protected function getTemplate() {
        // @todo check for ubuntu version and add/remove namevirtualhost
        $template =
            <<<'TEMPLATE'
 <VirtualHost ****IP ADDRESS****>
   ServerAdmin webmaster@localhost
 	ServerName ****SERVER NAME****
 	DocumentRoot ****WEB ROOT****
 	<Directory ****WEB ROOT****>
 		Options Indexes FollowSymLinks MultiViews
        DirectoryIndex Interface.php
 		AllowOverride All
 		Require all granted
 	</Directory>
   ErrorLog /var/log/apache2/error.log
   CustomLog /var/log/apache2/access.log combined
 </VirtualHost>

TEMPLATE;

        return $template ;
    }


}
