<?php

/*************************************
 *      Generated Autopilot file      *
 *     ---------------------------    *
 *Autopilot Generated By PTDeploy *
 *     ---------------------------    *
 *************************************/

Namespace Core ;

class AutoPilotConfigured extends AutoPilot {

    public $steps ;

    public function __construct() {
        $this->setSteps();
    }

    private function setSteps() {

        $this->steps =
            array(
                array ( "Logging" => array( "log" => array( "log-message" => "Lets begin with ensuring the Project Container is initialized" ), ) ),
                array ( "Project" => array( "container" => array(
                    "proj-container" => "<%tpl.php%>dap_proj_cont_dir</%tpl.php%>"
                ), ) , ) ,

                array ( "Logging" => array( "log" => array( "log-message" => "Lets initialize our new download directory as a ptdeploy project"), ) ),
                array ( "Project" => array( "init" => array(), ) , ) ,

                array ( "Logging" => array( "log" => array( "log-message" => "Next create our virtual host"), ) ),
                array ( "ApacheVHostEditor" => array( "add" => array (
                    "guess" => true,
                    "vhe-docroot" => "<%tpl.php%>dap_proj_cont_dir</%tpl.php%>",
                    "vhe-url" => "<%tpl.php%>dap_apache_vhost_url</%tpl.php%>",
                    "vhe-ip-port" => "<%tpl.php%>dap_apache_vhost_ip</%tpl.php%>",
                    "vhe-vhost-dir" => "/etc/apache2/sites-available",
                    "vhe-template" => $this->getTemplate(),
                ), ), ),

                array ( "Logging" => array( "log" => array( "log-message" => "Now lets restart Apache so we are serving our new application version", ), ), ),
                array ( "ApacheControl" => array( "restart" => array(
                    "guess" => true,
                ), ), ),

                array ( "Logging" => array( "log" => array("log-message" => "Our deployment is done" ), ), ),
            );
    }

    private function getTemplate() {
        $template =
            <<<'TEMPLATE'
 NameVirtualHost 0.0.0.0:80
 <VirtualHost 0.0.0.0:80>
   ServerAdmin webmaster@localhost
 	ServerName ****SERVER NAME****
 	DocumentRoot ****WEB ROOT****src
 	<Directory ****WEB ROOT****src>
 		Options Indexes FollowSymLinks MultiViews
 		AllowOverride All
 		Order allow,deny
 		allow from all
 	</Directory>
   ErrorLog /var/log/apache2/error.log
   CustomLog /var/log/apache2/access.log combined
 </VirtualHost>

#
# need to do something snakeoilyish before this will work
#
# NameVirtualHost 0.0.0.0:443
# <VirtualHost 0.0.0.0:443>
# 	 ServerAdmin webmaster@localhost
# 	 ServerName ****SERVER NAME****
 	 DocumentRoot ****WEB ROOT****src
   # SSLEngine on
   # SSLCertificateFile /etc/apache2/ssl/ssl.crt
   # SSLCertificateKeyFile /etc/apache2/ssl/ssl.key
   # SSLCertificateChainFile /etc/apache2/ssl/bundle.crt
# 	 <Directory ****WEB ROOT****src>
 #		 Options Indexes FollowSymLinks MultiViews
#		AllowOverride All
#		Order allow,deny
#		allow from all
#	</Directory>
#  ErrorLog /var/log/apache2/error.log
#  CustomLog /var/log/apache2/access.log combined
#  </VirtualHost>
TEMPLATE;

        return $template ;
    }


}
