<?php

/*************************************
 *      Generated Autopilot file      *
 *     ---------------------------    *
 *Autopilot Generated By Dapperstrano *
 *     ---------------------------    *
 *************************************/

Namespace Core ;

class AutoPilotConfigured extends AutoPilot {

    public $steps ;

    public function __construct() {
        $this->setSteps();
    }

    /* Steps */
    private function setSteps() {

        $this->steps =
            array(
                array ( "Logging" => array( "log" =>
                    array( "log-message" => "Lets begin invoking Code and Data on environment <%tpl.php%>env_name</%tpl.php%>"),
                ) ),
                array ( "Invoke" => array( "data" =>
                    array("ssh-data" => $this->setSSHData() ),
                    array("environment-name" => "<%tpl.php%>env_name</%tpl.php%>" ),
                ) , ) ,
                array ( "Logging" => array( "log" =>
                    array( "log-message" => "Invoking Code and Data on environment <%tpl.php%>env_name</%tpl.php%> complete"),
                ) ),
            );

    }

    private function setSSHData() {
        $timeDrop = time();
        $sshData = <<<"SSHDATA"
cd ****gen_env_tmp_dir****
git clone -b ****dap_git_custom_branch**** --no-checkout --depth 1 ****dap_git_repo_url**** dapper$timeDrop
cd dapper$timeDrop
git show HEAD:build/config/dapperstrano/autopilots/****gen_env_name****-node-install-code-data.php > ****gen_env_tmp_dir********gen_env_name****-node-install-code-data.php
rm -rf ****gen_env_tmp_dir****dapper$timeDrop
cd ****gen_env_tmp_dir****
sudo dapperstrano autopilot execute ****gen_env_name****-node-install-code-data.php
sudo chown -R www-data ****dap_proj_cont_dir****current/src
sudo rm ****gen_env_name****-node-install-code-data.php
SSHDATA;
        return $sshData ;
    }

}
