<?php

/*************************************
 *      Generated Autopilot file      *
 *     ---------------------------    *
 *Autopilot Generated By Dapperstrano *
 *     ---------------------------    *
 *************************************/

Namespace Core ;

class AutoPilotConfigured extends AutoPilot {

    public $steps ;

    public function __construct() {
        $this->setSteps();
    }

    /* Steps */
    private function setSteps() {

        $this->steps =
            array(
                array ( "Logging" => array( "log" =>
                    array( "log-message" => "Lets enforce our Revisions"),
                ) ),
                array ( "Version" => array( "rollback" =>
                    array( "container" => "****dap_proj_cont_dir****"),
                    array( "limit" => "****dap_version_num_revisions****"),
                ) , ) ,
                array ( "Logging" => array( "log" =>
                    array( "log-message" => "Now lets restart Apache so we are serving our new application"),
                ) ),
                array ( "ApacheControl" => array( "restart" =>
                    array() ,
                ) , ) ,
                array ( "Logging" => array( "log" =>
                    array( "log-message" => "Our deployment is done"),
                ) ),
            );


    }


}
