<?php

/*************************************
*      Generated Autopilot file      *
*     ---------------------------    *
*Autopilot Generated By PTDeploy *
*     ---------------------------    *
*************************************/

Namespace Core ;

class AutoPilotConfigured extends AutoPilot {

    public $steps ;

    public function __construct() {
	    $this->setSteps();
    }

    protected function setSteps() {

	    $this->steps =
	      array(

              array ( "Logging" => array( "log" => array( "log-message" => "Starting PTDeploy Application Configuration of Virtual Machine Host"), ) ),

              array ( "Logging" => array( "log" => array( "log-message" => "Create our host file entry for our local URL"), ) ),
              array ( "HostEditor" => array( "add" => array (
                  "guess" => true,
                  "host-name" => "<%tpl.php%>dap_apache_vhost_url</%tpl.php%>",
                  "host-ip" => $this->getCurrentTargetFromPapyrus(),
              ), ), ),

              array ( "Logging" => array( "log" => array( "log-message" => "PTDeploy Application Configuration of Virtual Machine Host Complete", ), ), ),

	      );

	  }

    protected function getCurrentTargetFromPapyrus() {
        $pf = \Model\AppConfig::getProjectVariable("ptvirtualize-box", true) ;
        if (is_array($pf) && count($pf)>0) {
            return $pf["target"] ; }
        return null ;
    }
}
