<?php

/*************************************
*      Generated Autopilot file      *
*     ---------------------------    *
*Autopilot Generated By Dapperstrano *
*     ---------------------------    *
*************************************/

Namespace Core ;

class AutoPilotConfigured extends AutoPilot {

    public $steps ;

    public function __construct() {
	    $this->setSteps();
    }

    /* Steps */
    private function setSteps() {

	    $this->steps =
	      array(
              array ( "Git" => array(
                  "gitDeletorExecute" => true,
                  "gitDeletorCustomFolder" => "****dap_proj_cont_dir****"
              ), ) ,
              array ( "HostEditor" => array(
                  "hostEditorDeletionExecute" => true,
                  "hostEditorDeletionIP" => "****dap_apache_vhost_ip****",
                  "hostEditorDeletionURI" => "****dap_apache_vhost_url****.local",
              ) , ) ,
              array ( "VHostEditor" => array(
                  "virtualHostEditorDeletionExecute" => "boolean",
                  "virtualHostEditorDeletionDirectory" => "/etc/apache2/sites-available",
                  "virtualHostEditorDeletionTarget" => "****dap_apache_vhost_url****",
                  "virtualHostEditorDeletionVHostDisable" => false,
                  "virtualHostEditorDeletionSymLinkDirectory" => "/etc/apache2/sites-enabled",
                  "virtualHostEditorDeletionApacheCommand" => "apache2",
              ) , ) ,
              array ( "DBInstall" => array(
                  "dbDropExecute" => true,
                  "dbDropDBHost" => "****dap_db_ip_address****",
                  "dbDropDBName" => "****dap_db_name****",
                  "dbDropDBRootUser" => "****dap_db_admin_user_name****",
                  "dbDropDBRootPass" => "****dap_db_admin_user_pass****",
                  "dbDropUserExecute" => true,
                  "dbDropDBUser" => "****dap_db_app_user_name****",
              ) , ) ,
              array ( "ApacheControl" => array(
                  "apacheCtlRestartExecute" => true,
              ) , ) ,
	      );

	  }

}
