<?php

/*************************************
*      Generated Autopilot file      *
*     ---------------------------    *
*Autopilot Generated By Dapperstrano *
*     ---------------------------    *
*************************************/

Namespace Core ;

class AutoPilotConfigured extends AutoPilot {

    public $steps ;

    public function __construct() {
	    $this->setSteps();
        $this->setRevisionFolderName();
        $this->calculateVHostDocRoot();
        $this->setVHostTemplate();
    }

    /* Steps */
    private function setSteps() {

	    $this->steps =
            array(
                array ( "Logging" => array( "log" =>
                array( "log-message" => "Lets begin invoking Revision Enforcement on environment <%tpl.php%>env_name</%tpl.php%>"),
                ) ),
                array ( "Invoke" => array( "data" =>
                array("ssh-data" => $this->setSSHData() ),
                    array("environment-name" => "<%tpl.php%>env_name</%tpl.php%>" ),
                ) , ) ,
                array ( "Logging" => array( "log" =>
                array( "log-message" => "Invoking Revision Enforcement on environment <%tpl.php%>env_name</%tpl.php%> complete"),
                ) ),
            );
	      array(
          array ( "Project" => array(
                    "projectContainerInitExecute" => true,
                    "projectContainerDirectory" => "****dap_proj_cont_dir****",
          ) , ) ,
          array ( "Git" => array(
                    "gitCheckoutExecute" => true,
                    "gitCheckoutProjectOriginRepo" => "****dap_git_repo_url****",
                    "gitCheckoutCustomCloneFolder" => "",
                    "gitCheckoutCustomBranch" => "****dap_git_custom_branch****",
                    "gitCheckoutWebServerUser" => "www-data",
          ) , ) ,
          array ( "Project" => array(
                    "projectInitializeExecute" => true,
          ) , ) ,
          array ( "VHostEditor" => array(
                    "virtualHostEditorAdditionExecute" => true,
                    "virtualHostEditorAdditionDocRoot" => "",
                    "virtualHostEditorAdditionURL" => "****dap_apache_vhost_url****",
                    "virtualHostEditorAdditionIp" => "****dap_apache_vhost_ip****",
                    "virtualHostEditorAdditionTemplateData" => "",
                    "virtualHostEditorAdditionDirectory" => "/etc/apache2/sites-available",
                    "virtualHostEditorAdditionFileSuffix" => "",
                    "virtualHostEditorAdditionVHostEnable" => true,
                    "virtualHostEditorAdditionSymLinkDirectory" => "/etc/apache2/sites-enabled",
                    "virtualHostEditorAdditionApacheCommand" => "apache2",
          ) , ) ,
          array ( "DBConfigure" => array(
                    "dbResetExecute" => true,
                    "dbResetPlatform" => "****dap_db_platform****",
          ) , ) ,
          array ( "DBConfigure" => array(
                    "dbConfigureExecute" => true,
                    "dbConfigureDBHost" => "****dap_db_ip_address****",
                    "dbConfigureDBUser" => "****dap_db_app_user_name****",
                    "dbConfigureDBPass" => "****dap_db_app_user_pass****",
                    "dbConfigureDBName" => "****dap_db_name****",
                    "dbConfigurePlatform" => "****dap_db_platform****",
          ) , ) ,
          array ( "DBInstall" => array(
                    "dbDropExecute" => true,
                    "dbDropDBHost" => "****dap_db_ip_address****",
                    "dbDropDBName" => "****dap_db_name****",
                    "dbDropDBRootUser" => "****dap_db_admin_user_name****",
                    "dbDropDBRootPass" => "****dap_db_admin_user_pass****",
                    "dbDropUserExecute" => true,
                    "dbDropDBUser" => "****dap_db_app_user_name****",
          ) , ) ,
          array ( "DBInstall" => array(
                    "dbInstallExecute" => true,
                    "dbInstallDBHost" => "****dap_db_ip_address****",
                    "dbInstallDBUser" => "****dap_db_app_user_name****",
                    "dbInstallDBPass" => "****dap_db_app_user_pass****",
                    "dbInstallDBName" => "****dap_db_name****",
                    "dbInstallDBRootUser" => "****dap_db_admin_user_name****",
                    "dbInstallDBRootPass" => "****dap_db_admin_user_pass****",
          ) , ) ,
              array ( "Version" => array(
                  "versionExecute" => true,
                  "versionAppRootDirectory" => "****dap_proj_cont_dir****",
                  "versionArrayPointToRollback" => "0",
                  "versionLimit" => "****dap_version_num_revisions****",
              ) , ) ,
              array ( "ApacheControl" => array(
                  "apacheCtlRestartExecute" => true,
              ) , ) ,
	      );

	  }


 private function setRevisionFolderName() {
   $this->steps[1]["Git"]["gitCheckoutCustomCloneFolder"] = time() ;
 }


 // This function will set the vhost template for your Virtual Host
 // You need to call this from your constructor
 private function calculateVHostDocRoot() {
    $this->steps[3]["VHostEditor"]["virtualHostEditorAdditionDocRoot"]
         = "****dap_proj_cont_dir****".$this->steps[1]["Git"]["gitCheckoutCustomCloneFolder"];
 }

 // This function will set the vhost template for your Virtual Host
 // You need to call this from your constructor
 private function setVHostTemplate() {
   $this->steps[3]["VHostEditor"]["virtualHostEditorAdditionTemplateData"] =
  <<<'TEMPLATE'
 NameVirtualHost ****IP ADDRESS****:80
 <VirtualHost ****IP ADDRESS****:80>
   ServerAdmin webmaster@localhost
 	ServerName ****SERVER NAME****
 	DocumentRoot ****WEB ROOT****/src
 	<Directory ****WEB ROOT****/src>
 		Options Indexes FollowSymLinks MultiViews
 		AllowOverride All
 		Order allow,deny
 		allow from all
 	</Directory>
   ErrorLog /var/log/apache2/error.log
   CustomLog /var/log/apache2/access.log combined
 </VirtualHost>

 NameVirtualHost ****IP ADDRESS****:443
 <VirtualHost ****IP ADDRESS****:443>
 	 ServerAdmin webmaster@localhost
 	 ServerName ****SERVER NAME****
 	 DocumentRoot ****WEB ROOT****/src
   # SSLEngine on
 	 # SSLCertificateFile /etc/apache2/ssl/ssl.crt
   # SSLCertificateKeyFile /etc/apache2/ssl/ssl.key
   # SSLCertificateChainFile /etc/apache2/ssl/bundle.crt
 	 <Directory ****WEB ROOT****/src>
 		 Options Indexes FollowSymLinks MultiViews
		AllowOverride All
		Order allow,deny
		allow from all
	</Directory>
  ErrorLog /var/log/apache2/error.log
  CustomLog /var/log/apache2/access.log combined
  </VirtualHost>
TEMPLATE;
}


}
