<?php

/*************************************
 *      Generated Autopilot file      *
 *     ---------------------------    *
 *Autopilot Generated By Dapperstrano *
 *     ---------------------------    *
 *************************************/

Namespace Core ;

class AutoPilotConfigured extends AutoPilot {

  public $steps ;
  public $swaps ;

  public function __construct() {
    $this->setSteps();
    $this->setSSHData();
  }

  /* Steps */
  private function setSteps() {

    $this->steps =
      array(
        array ( "InvokeSSH" => array(
          "sshInvokeSSHDataExecute" => true,
          "sshInvokeSSHDataData" => "",
          "sshInvokeServers" => array(
              ****gen_srv_array_text****
            ),
        ) , ) ,
        );

    }


//
// This function will set the sshInvokeSSHDataData variable with the data that
// you need in it. Call this in your constructor
//
  private function setSSHData() {
    $timeDrop = time();
    $this->steps[0]["InvokeSSH"]["sshInvokeSSHDataData"] = <<<"SSHDATA"
cd ****CURRENT_ENVIRONMENT_TEMP_DIR****
git clone -b ****gitCheckoutProjectCustomBranch**** --no-checkout --depth 1 ****gitCheckoutProjectOriginRepo**** dapper$timeDrop
cd dapper$timeDrop
git show HEAD:build/config/dapperstrano/autopilots/****CURRENT_ENVIRONMENT_NAME****-install-enforce-revisions.php > ****CURRENT_ENVIRONMENT_TEMP_DIR********CURRENT_ENVIRONMENT_NAME****-install-enforce-revisions.php
rm -rf ****CURRENT_ENVIRONMENT_TEMP_DIR****dapper$timeDrop
cd ****CURRENT_ENVIRONMENT_TEMP_DIR****
sudo dapperstrano autopilot execute ****CURRENT_ENVIRONMENT_NAME****-install-enforce-revisions.php
sudo chown -R www-data ****projectContainerDirectory****current/src
sudo rm ****CURRENT_ENVIRONMENT_NAME****-install-enforce-revisions.php
SSHDATA;
  }

}
