<?php

/*************************************
 *      Generated Autopilot file      *
 *     ---------------------------    *
 *Autopilot Generated By Dapperstrano *
 *     ---------------------------    *
 *************************************/

Namespace Core ;

class AutoPilotConfigured extends AutoPilot {

  public $steps ;

  public function __construct() {
    $this->setSteps();
    // $this->setSSHData();
  }

  /* Steps */
  private function setSteps() {

    $this->steps =
      array(
        array ( "Console" => array( "log" =>
          array( "console-log-message" => "Send this to the console"),
        ) ),
        array ( "Console" => array( "log" =>
          array( "console-log-message" => "Send this too"),
        ) ),
        array ( "Console" => array( "log" =>
          array( "console-log-message" => "then Send this there"),
        ) ),
        array ( "DeveloperTools" => array( "install" => array() ) ),
      );

    }


//
// This function will set the sshInvokeSSHDataData variable with the data that
// you need in it. Call this in your constructor
//
  private function setSSHData() {
    $this->steps[1]["InvokeSSH"][0]["ssh-invoke-ssh-data"] = <<<"SSHDATA"
cd /tmp/
echo bumface
SSHDATA;
  }

}
